CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Table des utilisateurs (synchronisée avec Firebase Auth)
CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(150) NOT NULL UNIQUE,
    email VARCHAR(254) NOT NULL UNIQUE,
    is_staff BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Table des Chefs de projet
CREATE TABLE IF NOT EXISTS public.chefs_de_projet (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(255) NOT NULL,
    specialite VARCHAR(255) NOT NULL DEFAULT '',
    email VARCHAR(255) NOT NULL UNIQUE,
    max_creneaux_entretien INTEGER NOT NULL DEFAULT 30,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_chefs_nom ON public.chefs_de_projet(nom);

-- Table des Étudiants
CREATE TABLE IF NOT EXISTS public.etudiants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(255) NOT NULL,
    prenom VARCHAR(255) NOT NULL,
    adresse_email VARCHAR(255) NOT NULL UNIQUE,
    parcours VARCHAR(20) NOT NULL DEFAULT 'I2026',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_etudiants_email ON public.etudiants(adresse_email);

-- Table des Sélections / Vœux
CREATE TABLE IF NOT EXISTS public.selections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    etudiant_id BIGINT NOT NULL REFERENCES public.etudiants(id) ON DELETE CASCADE,
    chef_de_projet_id BIGINT NOT NULL REFERENCES public.chefs_de_projet(id) ON DELETE CASCADE,
    priorite INTEGER DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_selection_etudiant_chef UNIQUE(etudiant_id, chef_de_projet_id)
);

-- Table des Disponibilités Chefs (40 slots de 15min)
CREATE TABLE IF NOT EXISTS public.disponibilite_binaire_chefprojet (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chef_de_projet_id BIGINT NOT NULL REFERENCES public.chefs_de_projet(id) ON DELETE CASCADE,
    date DATE NOT NULL,
    slot1 VARCHAR(1) DEFAULT '0', slot2 VARCHAR(1) DEFAULT '0', slot3 VARCHAR(1) DEFAULT '0', slot4 VARCHAR(1) DEFAULT '0',
    slot5 VARCHAR(1) DEFAULT '0', slot6 VARCHAR(1) DEFAULT '0', slot7 VARCHAR(1) DEFAULT '0', slot8 VARCHAR(1) DEFAULT '0',
    slot9 VARCHAR(1) DEFAULT '0', slot10 VARCHAR(1) DEFAULT '0', slot11 VARCHAR(1) DEFAULT '0', slot12 VARCHAR(1) DEFAULT '0',
    slot13 VARCHAR(1) DEFAULT '0', slot14 VARCHAR(1) DEFAULT '0', slot15 VARCHAR(1) DEFAULT '0', slot16 VARCHAR(1) DEFAULT '0',
    slot17 VARCHAR(1) DEFAULT '0', slot18 VARCHAR(1) DEFAULT '0', slot19 VARCHAR(1) DEFAULT '0', slot20 VARCHAR(1) DEFAULT '0',
    slot21 VARCHAR(1) DEFAULT '0', slot22 VARCHAR(1) DEFAULT '0', slot23 VARCHAR(1) DEFAULT '0', slot24 VARCHAR(1) DEFAULT '0',
    slot25 VARCHAR(1) DEFAULT '0', slot26 VARCHAR(1) DEFAULT '0', slot27 VARCHAR(1) DEFAULT '0', slot28 VARCHAR(1) DEFAULT '0',
    slot29 VARCHAR(1) DEFAULT '0', slot30 VARCHAR(1) DEFAULT '0', slot31 VARCHAR(1) DEFAULT '0', slot32 VARCHAR(1) DEFAULT '0',
    slot33 VARCHAR(1) DEFAULT '0', slot34 VARCHAR(1) DEFAULT '0', slot35 VARCHAR(1) DEFAULT '0', slot36 VARCHAR(1) DEFAULT '0',
    slot37 VARCHAR(1) DEFAULT '0', slot38 VARCHAR(1) DEFAULT '0', slot39 VARCHAR(1) DEFAULT '0', slot40 VARCHAR(1) DEFAULT '0',
    CONSTRAINT uq_dispo_chef_date UNIQUE(chef_de_projet_id, date)
);

-- Table des Disponibilités Étudiants (40 slots de 15min)
CREATE TABLE IF NOT EXISTS public.disponibilite_binaire_etudiant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    etudiant_id BIGINT NOT NULL REFERENCES public.etudiants(id) ON DELETE CASCADE,
    date DATE NOT NULL,
    slot1 VARCHAR(1) DEFAULT '0', slot2 VARCHAR(1) DEFAULT '0', slot3 VARCHAR(1) DEFAULT '0', slot4 VARCHAR(1) DEFAULT '0',
    slot5 VARCHAR(1) DEFAULT '0', slot6 VARCHAR(1) DEFAULT '0', slot7 VARCHAR(1) DEFAULT '0', slot8 VARCHAR(1) DEFAULT '0',
    slot9 VARCHAR(1) DEFAULT '0', slot10 VARCHAR(1) DEFAULT '0', slot11 VARCHAR(1) DEFAULT '0', slot12 VARCHAR(1) DEFAULT '0',
    slot13 VARCHAR(1) DEFAULT '0', slot14 VARCHAR(1) DEFAULT '0', slot15 VARCHAR(1) DEFAULT '0', slot16 VARCHAR(1) DEFAULT '0',
    slot17 VARCHAR(1) DEFAULT '0', slot18 VARCHAR(1) DEFAULT '0', slot19 VARCHAR(1) DEFAULT '0', slot20 VARCHAR(1) DEFAULT '0',
    slot21 VARCHAR(1) DEFAULT '0', slot22 VARCHAR(1) DEFAULT '0', slot23 VARCHAR(1) DEFAULT '0', slot24 VARCHAR(1) DEFAULT '0',
    slot25 VARCHAR(1) DEFAULT '0', slot26 VARCHAR(1) DEFAULT '0', slot27 VARCHAR(1) DEFAULT '0', slot28 VARCHAR(1) DEFAULT '0',
    slot29 VARCHAR(1) DEFAULT '0', slot30 VARCHAR(1) DEFAULT '0', slot31 VARCHAR(1) DEFAULT '0', slot32 VARCHAR(1) DEFAULT '0',
    slot33 VARCHAR(1) DEFAULT '0', slot34 VARCHAR(1) DEFAULT '0', slot35 VARCHAR(1) DEFAULT '0', slot36 VARCHAR(1) DEFAULT '0',
    slot37 VARCHAR(1) DEFAULT '0', slot38 VARCHAR(1) DEFAULT '0', slot39 VARCHAR(1) DEFAULT '0', slot40 VARCHAR(1) DEFAULT '0',
    CONSTRAINT uq_dispo_etud_date UNIQUE(etudiant_id, date)
);

-- Table des Rendez-vous validés
CREATE TABLE IF NOT EXISTS public.rendez_vous (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL,
    heure TIME NOT NULL,
    heure_fin TIME NOT NULL,
    chef_de_projet_id BIGINT NOT NULL REFERENCES public.chefs_de_projet(id) ON DELETE CASCADE,
    etudiant_id BIGINT NOT NULL REFERENCES public.etudiants(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_rdv_chef_creneau UNIQUE(chef_de_projet_id, date, heure),
    CONSTRAINT uq_rdv_etudiant_creneau UNIQUE(etudiant_id, date, heure)
);

-- Table des Évaluations (notes A, B, C, D)
CREATE TABLE IF NOT EXISTS public.evaluations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chef_de_projet_id BIGINT NOT NULL REFERENCES public.chefs_de_projet(id) ON DELETE CASCADE,
    etudiant_id BIGINT NOT NULL REFERENCES public.etudiants(id) ON DELETE CASCADE,
    note VARCHAR(5) NOT NULL,
    commentaire TEXT DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_eval_chef_etudiant UNIQUE(chef_de_projet_id, etudiant_id)
);

-- Table des Affectations finales
CREATE TABLE IF NOT EXISTS public.affectation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chef_de_projet_id BIGINT NOT NULL REFERENCES public.chefs_de_projet(id) ON DELETE CASCADE,
    etudiant_id BIGINT NOT NULL UNIQUE REFERENCES public.etudiants(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Configuration RLS (Row Level Security)
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chefs_de_projet ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.etudiants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.selections ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.disponibilite_binaire_chefprojet ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.disponibilite_binaire_etudiant ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rendez_vous ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.evaluations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.affectation ENABLE ROW LEVEL SECURITY;

DO $$
DECLARE
    t text;
    tables_list text[] := ARRAY[
        'users', 'chefs_de_projet', 'etudiants', 'selections',
        'disponibilite_binaire_chefprojet', 'disponibilite_binaire_etudiant',
        'rendez_vous', 'evaluations', 'affectation'
    ];
BEGIN
    FOREACH t IN ARRAY tables_list LOOP
        EXECUTE format('DROP POLICY IF EXISTS "Public access" ON public.%I', t);
        EXECUTE format('CREATE POLICY "Public access" ON public.%I FOR ALL USING (true) WITH CHECK (true)', t);
    END LOOP;
END $$;
